f=open('student.txt',mode='r',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('student.txt',mode='w',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('student.txt',mode='a',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('student1.txt',mode='x',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('student.txt',mode='r+',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('student.txt',mode='w+',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('student.txt',mode='a+',encoding='utf-8')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image.jpg',mode='rb')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image.jpg',mode='wb')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image1.jpg',mode='xb')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image.jpg',mode='ab')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image.jpg',mode='rb+')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image.jpg',mode='wb+')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)
f=open('image.jpg',mode='ab+')
print('File Name:',f.name)
print('File Mode:',f.mode)
print('File Readable:',f.readable())
print('File Writable:',f.writable())
print('File Closed:',f.closed)
f.close()
print('File Closed:',f.closed)