from datetime import datetime
dt=datetime.today()
print(dt)
newd1=dt.strftime("%B %d %Y")
print(newd1)
newd2=dt.strftime("%d/%b/%Y")
print(newd2)
newd3=dt.strftime("%d-%m-%Y")
print(newd3)
newd4=dt.strftime("%H:%M:%S")
print(newd4)
newd5=dt.strftime("%I:%M:%S")
print(newd5)
print(type(dt))
print(type(newd1))