import os
from PIL import Image,ImageEnhance,ImageFilter
imag1=Image.open(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Sample Images\dog.jpg')
imag1.show()
imag1.save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\dog.pdf')
max_size=(250,350)
imag1.thumbnail(max_size)
imag1.save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\dog.bmp')
for item in os.listdir():
    if item.endswith('.jpg'):
        imag1=Image.open(item)
        filename,extention=os.path.splitext(item)
        imag1.save(f'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\{filename}.png')
enhancer=ImageEnhance.Sharpness(imag1)
enhancer.enhance(0).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\sharpness0.jpg')
enhancer.enhance(1).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\sharpness1.jpg')
enhancer.enhance(2).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\sharpness2.jpg')
enhancer=ImageEnhance.Color(imag1)
enhancer.enhance(0).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\color0.jpg')
enhancer.enhance(1).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\color1.jpg')
enhancer.enhance(2).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\color2.jpg')
enhancer=ImageEnhance.Brightness(imag1)
enhancer.enhance(0).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\brightness0.jpg')
enhancer.enhance(1).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\brightness1.jpg')
enhancer.enhance(2).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\brightness2.jpg')
enhancer=ImageEnhance.Contrast(imag1)
enhancer.enhance(0).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\contrast0.jpg')
enhancer.enhance(1).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\contrast1.jpg')
enhancer.enhance(2.5).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\contrast2.jpg')
imag1.filter(ImageFilter.GaussianBlur()).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\blur1.jpg')
imag1.filter(ImageFilter.GaussianBlur(radius=16)).save(r'E:\Python\Chapter-20(Python Modules)\C-Edit Images Uging Pyhton\Edited Images\blur2.jpg')