f=open('student.txt',mode='w')
n=f.write('Hello')
print(n)
f.close()
f=open('student.txt',mode='w')
f.write('Name\n')
f.write('Satyam\n')
print(n)
f.close()
f=open('student1.txt',mode='x')
n=f.write('Hello\nJi')
print(n)
f.close()
f=open('student1.txt',mode='a')
f.write('Kya Hal Hai.')
f.close()