stu={101:'Rahul',102:'Raj',103:'Sonam'}
print("Original Dict:")
print(stu)
print(id(stu))
returned_value1=stu.setdefault(101)
print("After setdefault Dict:")
print(stu)
print(id(stu))
print("Returned Value:",returned_value1)
returned_value2=stu.setdefault(102,'Satyam')
print("After setdefault Dict:")
print(stu)
print(id(stu))
print("Returned Value:",returned_value2)
returned_value3=stu.setdefault(104,'Satyam')
print("After setdefault Dict:")
print(stu)
print(id(stu))
print("Returned Value:",returned_value3)
returned_value4=stu.setdefault(105)
print("After setdefault Dict:")
print(stu)
print(id(stu))
print("Returned Value:",returned_value4)