# Integer
print("********** Integer ***********")
print("{}".format(15))
print("{:d}".format(15))
print("{0:d}".format(15))
print("{num:d}".format(num=15))
print("{num:5d}".format(num=15))
print("{num:05d}".format(num=15))
print("{num:+5d}".format(num=15))
print("{num:<5d}".format(num=15))
print("{num:*<5d}".format(num=15))
print("{num:*>5d}".format(num=15))
print("{num:^5d}".format(num=15))
print("{num:*^5d}".format(num=15))