# String
print("********** String ***********")
print("{}".format("Geek"))
print("{:8}".format("Geek"))
print("{:<8}".format("Geek"))
print("{:*<8}".format("Geek"))
print("{:>8}".format("Geek"))
print("{:*>8s}".format("Geek"))
print("{:^8s}".format("Geek"))
print("{:*^8s}".format("Geek"))
print("***** Truncating String *****")
print("{:.3s}".format("GeekShows"))
print("{:8.3s}".format("GeekShows"))
print("{:*<8.3s}".format("GeekShows"))
print("{:>8.3s}".format("GeekShows"))
print("{:*>8.3s}".format("GeekShows"))
print("{:^8.3s}".format("GeekShows"))
print("{:*^8.3s}".format("GeekShows"))
